### ISSUE TITLE
Eco, power an quiet mode

### ISSUE THREAD

**Issue by macjl** [jhthorsen/homebridge-tasmota-aircon-http#1]
Hello,

I discovered your plugin, and tried it today. It works very well !
I’m using a custom way to control my A/C from Homebridge based on a dedicated raspberry pi with IR. But I think your approch is far better than mine !

I use the eco, power and quiet mode very often, and did not see it in your plugin. Do you have plan to implement it as custom HomeKit characteristics in the future ?

**Comment by jhthorsen** [comment]
I'm not sure how I would do that. The [HeaterCoolor](https://developers.homebridge.io/#/service/HeaterCooler) component does not seem to support that.

I guess it could be added as extra buttons, but that doesn't seem very user friendly.

What do you mean when you say you use "power" often? (I read that as on/off)

Open to suggestions 👍

**Comment by macjl** [comment]
Hello,
My use case is that all night, I’m setting the Quiet mode on automatically, because A/C is too loud to sleep in normal mode. 
For eco mode, it is set when away from home, to save power.  And I use the Power mode manually, for example before going back to home after a long period, to heat the house as fast as possible.

For the implementation, I think switches within the accessory could be a good option. Even if the HeaterCooler doesn’t integrate it by default, you could add custom characteristics, and the switches will be visible only inside the HeaterCooler device. Of course, these switches could be optional in Homebridge config for those who don’t need them. Do you think it’s acceptable ?

**Comment by jhthorsen** [comment]
I wonder if "power" is the same as "Turbo" under "IRhvac" on https://tasmota.github.io/docs/Commands/#ir-remote... I don't have that setting on my aircon, but maybe you can check it if you have a IR receiver that outputs IRhvac?

I have to try out the implementation, but in "worst case scenario" it sounds like having separate buttons would work, since you only need them for automation. I'm not a huge fan of adding custom characteristics, since I think the result is a messy user experience in the Home app.

Not quite sure when I will find time to look at this, but sounds like a fun and not too hard addition.

**Comment by jhthorsen** [comment]
I think you solved this in #2.
